### ISSUE TITLE
0.3.2 whell包存在的问题

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/oneflow_convert_tools#26]
1. 不支持PreLU
2. Codegen的时候由于随机产生的数可能比较大，导致没有bn的网络比如googlenet会精度爆炸（这是猜测，因为本地可以正常运行，ci有概率挂，所以codegen暂时没有放入ci）
3. oneflow2onnx生成的模型会立马被删除，master代码已经解决这个问题，解决上面2个问题之后一起发布0.3.3 whell包。

计划分2个pr分别解决。

**Comment by daquexian** [comment]
> 不支持PreLU

这个原本有个 pr 现在失联了 https://github.com/Oneflow-Inc/oneflow/pull/4181
