### ISSUE TITLE
Eager Oneflow2onnx

### ISSUE THREAD

**Issue by hhhfccz** [Oneflow-Inc/oneflow_convert_tools#40]
最开始删掉所有包含有`@flow`的装饰器，还有flow.experimental，flow.checkpoint等

## examples.models

将模型迁移到Graph上

```python
# 假设class AlexNet存在
def alexnet(pretrained: bool = False, progress: bool = True, **kwargs: Any) -> AlexNet:
    model = AlexNet(**kwargs)
    return model


def test_alexnet():
    alexnet_module = alexnet()
    alexnet_module.eval().to("cuda")
	
    # Graph添加到oneflow_onnx/oneflow2onnx/util.py文件中
    alexnet_graph = Graph(alexnet_module)
	
    # 这里把job换成了graph
    convert_to_onnx_and_check(
        alexnet_graph, 
        flow_weight_dir="./examples/oneflow2onnx/models/alexnet_oneflow_model", 
        onnx_model_path="/tmp"
    )

```

其中Graph为

```python
class Graph(flow.nn.Graph):
    def __init__(self, module):
        super().__init__()
        self.m = module

    def build(self, x):
        out = self.m(x)
        return out
```

在[这里](https://github.com/Oneflow-Inc/oneflow_convert_tools/blob/bb38c52954facbfe977e09c7e4706b7563a7b50c/oneflow_onnx/onnx_wrapper.py#L380)也有叫Graph的类，我打算修改成OneflowGraph，跟[tvm里](https://github.com/Oneflow-Inc/tvm/blob/main/python/tvm/relay/frontend/oneflow.py#L1834)一致

## oneflow2onnx.util

关于convert_to_onnx_and_check()函数

1. 把函数中的job换成graph(所有函数都得换)
2. 关于explicit_init参数，我不太清楚在lazy中[这段代码](https://github.com/Oneflow-Inc/oneflow_convert_tools/blob/main/oneflow_onnx/oneflow2onnx/util.py#L134-L143)的具体作用

关于export_onnx_model()函数，转换主函数

1. 我打算删除关于flow_weight_dir的if-else语句，可以放在后续Export主函数里面（我觉得直接assert必须输入model_dir_path要好一些，我在tvm里是这么做的）
2. 关于判断是否存在snapshot_done，在tvm中有更快的[方案](https://github.com/Oneflow-Inc/tvm/blob/main/python/tvm/relay/frontend/oneflow.py#L1772)，直接搬过来了

## oneflow2onnx.flow2onnx

关于ProcessFlowGraph函数

1. lazy中通过helper获取节点信息，现在的版本应该是得从repr(graph)里面自己提取，graph_proto(对应之前的job_func).helper返回是None，所以这里得加上test中体现的那些节电信息提取的脚本，也对应tvm的[这里](https://github.com/Oneflow-Inc/tvm/blob/main/python/tvm/relay/frontend/oneflow.py#L1787-L1827)。当然这个需要小修，因为最新的repr(graph)把data type也放进来了，可以单个提取，如下：

```python
shapes = {}
dtypes = {}
graph_str = repr(graph)
# print(graph_str)
size_where = 2
if "cuda" in graph_str:
    size_where = 3

p_size = re.compile(r"size=\(.*?\)", re.S)
p_type = re.compile(r"dtype=.*?,", re.S)
types = ["INPUT", "PARAMETER", "BUFFER", "OUTPUT"]

for t in types:
    data = re.finditer(t+":.*", graph_str)
    for i in data:
        attrs = i.group().split(":")
        size_str = re.findall(p_size, attrs[size_where])
        type_str = re.findall(p_type, attrs[size_where])
        assert size_str != [] or type_str != [], \
        "size should not be None, please check your inputs dtype"

        size_attr = size_str[0].replace("size=", "")
        type_attr = type_str[0].replace("dtype=", "")
        if size_attr[-2] == ",":
            size_attr = size_attr.replace(",", "")
        if type_attr[-1] == ",":
            type_str = type_attr.replace(",", "")

        data_size = tuple(map(int, size_attr[1:-1].split(", ")))
        node_name = attrs[1]
        shapes[node_name] = data_size
        dtypes[node_name] = STR_TO_FLOW[type_str]
            
```

关于nodes的存放，现有的oneflow2onnx是list模式，用helper.make_node()暂时不清楚会有什么问题

同时其中的get_inputs和get_outputs这些函数可以使用node.user_conf.node_name进行改动，也就是对应[这里](https://github.com/Oneflow-Inc/tvm/blob/main/python/tvm/relay/frontend/oneflow.py#L1498-L1528)

当然我觉得这个可能可以并入[这里](https://github.com/Oneflow-Inc/oneflow_convert_tools/blob/bb38c52954facbfe977e09c7e4706b7563a7b50c/oneflow_onnx/onnx_wrapper.py#L380)，在tvm中是这么做的

## oneflow_onnx

1. 关于_GraphCheck，可以改成`graph._is_compiled()`
2. 关于UpdateProto，好像有两个，[一](https://github.com/Oneflow-Inc/oneflow_convert_tools/blob/96696edd940d58187573d7531404e6b5054e3d56/oneflow_onnx/onnx_wrapper.py#L322)、[二](https://github.com/Oneflow-Inc/oneflow_convert_tools/blob/96696edd940d58187573d7531404e6b5054e3d56/oneflow_onnx/onnx_wrapper.py#L758)，或许需要改个名字
3. 关于MakeSure，可以改成assert吧
4. 关于获取数据MakeSlice，那几个参数应该可以提前存储好然后要用的时候直接提取吧，tvm里面我是先存好后面直接提取
5. 关于获取attr，好像比较复杂，不仅仅只有[这里](https://github.com/Oneflow-Inc/oneflow_convert_tools/blob/bb38c52954facbfe977e09c7e4706b7563a7b50c/oneflow_onnx/util.py#L166-L176)

```python
def parse_attr(attr):
    # Parse node_attr
    attrs = {}
    for a in attr:
        attr_str = str(attr[a])

        if attr_str[0:7] == "at_list":
            attr_str_ = attr_str.split(" ")[0]

            if attr_str_ == "at_list_float":
                attrs[a] = tuple(attr[a].at_list_float.val)
            elif attr_str_ == "at_list_int32":
                attrs[a] = tuple(attr[a].at_list_int32.val)
            elif attr_str_ == "at_list_int64":
                attrs[a] = tuple(attr[a].at_list_int64.val)

        elif attr_str.split(":")[0] == "at_string":
            attrs[a] = attr[a].at_string

        elif attr_str.split(" ")[0] == "at_shape":
            attrs[a] = tuple(list(attr[a].at_shape.dim))

        else:
            attr_str_ = attr_str.split(":")[0]
            if attr_str_ == "at_bool":
                attrs[a] = attr[a].at_bool
            elif attr_str_ == "at_double":
                attrs[a] = attr[a].at_double
            elif attr_str_ == "at_float":
                attrs[a] = attr[a].at_float
            elif attr_str_ == "at_int32":
                attrs[a] = attr[a].at_int32
            elif attr_str_ == "at_int64":
                attrs[a] = attr[a].at_int64

    return attrs
    
```

关于optimizer我没有详细看，应该也有一些类似上面的错误，比如命名的修改以及op中attrs信息的提取

**Comment by BBuf** [comment]
这里提的问题基本上都不存在，只要处理好nn.Graph的job和之前job_function拿到的job的对应关系就可以了，可以看最新提交的0.5.0pre 的pr。这个issue我关闭了。
